version: '3'
services:
  web:
    container_name: docker-node-mongo-app
    restart: always
    build: .
    ports:
      - '8000:8080'
    links:
      - 'mongo'
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'